import { MigrationInterface, QueryRunner } from 'typeorm';

export class addBrandItem1647968311244 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
        create table brands (
            id int generated by default as identity primary key,
            name varchar(100),
            created_at timestamptz not null,
            updated_at timestamptz not null
    )`);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
        drop table brands 
    `);
  }
}
