import { MigrationInterface, QueryRunner } from 'typeorm';

export class characteristics1647610029479 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
        create table characteristics (
          id int generated by default as identity primary key,
          code varchar(50),
          created_at timestamptz not null,
          updated_at timestamptz not null
        )
    `);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {}
}
