import { MigrationInterface, QueryRunner } from 'typeorm';

export class orders1648205928533 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      "CREATE TYPE type_of_payment AS ENUM ('Any card online', 'Payment in installments / Credit')",
    );

    await queryRunner.query(
      "CREATE TYPE type_of_service AS ENUM ('Service 1', 'Service 2', 'Service 3')",
    );

    await queryRunner.query(`
        create table orders (
          id int generated by default as identity primary key,
          total numeric(1000, 2) not null,
          city varchar(150) not null,
          street varchar(150) not null,
          house varchar(150) not null, 
          flat varchar(150) not null,
          payment_type type_of_payment not null,
          service type_of_service not null, 
          created_at timestamptz not null,
          updated_at timestamptz not null
        )
    `);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {}
}
