import { MigrationInterface, QueryRunner } from 'typeorm';

export class comment1648152690864 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
        create table comments (
          id int generated by default as identity primary key,
          username varchar(100),
          comment text,
          item_id int references items(id) on delete cascade,
          reply_id int references comments(id) on delete cascade,
          created_at timestamptz not null,
          updated_at timestamptz not null
        )
    `);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {}
}
